<a href="https://colab.research.google.com/github/prasadnikhil125-CHAUDHARY/business-data-analysis-ai-ml/blob/main/Filtering_%26_Sorting_Data_in_SQLite.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Library
import sqlite3
import requests
import pandas as pd

https://github.com/YBIFoundation/SQL/raw/main/DigitalMarketingAnalytics.sql

In [ ]:
url = 'https://github.com/YBIFoundation/SQL/raw/main/DigitalMarketingAnalytics.sql'
sql_script = requests.get(url).text

In [ ]:
sql_script

'BEGIN TRANSACTION;\nCREATE TABLE marketing(\nCustomer_ID INTEGER PRIMARY KEY,\nGender TEXT,\nAge INTEGER,\nCity TEXT,\nDevice TEXT,\nMarketing_Channel TEXT,\nCampaign TEXT,\nAd_Clicks INTEGER,\nImpressions INTEGER,\nSpend INTEGER,\nPurchased TEXT,\nSales INTEGER,\nOrder_Value INTEGER,\nPurchase_Date TEXT,\nCustomer_Segment TEXT\n);\nINSERT INTO "marketing" VALUES(100001,\'Male\',19,\'Hyderabad\',\'Mobile\',\'Google\',\'Summer Sale\',1106,18370,11890,\'Yes\',2979,2979,\'2025-04-30\',\'Returning\');\nINSERT INTO "marketing" VALUES(100002,\'Male\',53,\'Delhi\',\'Mobile\',\'Instagram\',\'Festive Offer\',839,9615,3443,\'No\',0,0,\'2025-12-24\',\'New\');\nINSERT INTO "marketing" VALUES(100003,\'Female\',39,\'Mumbai\',\'Mobile\',\'Facebook\',\'Summer Sale\',195,3669,1853,\'No\',0,0,\'2025-01-23\',\'New\');\nINSERT INTO "marketing" VALUES(100004,\'Female\',52,\'Delhi\',\'Tablet\',\'Google\',\'Flash Sale\',1180,12350,18022,\'Yes\',3065,3065,\'2025-05-29\',\'Returning\');\nINSERT INTO "marketing" VALUES(100005,\'Male\',32,\'Chennai\',\'Mobile\',\'Instagram\',\'Flash Sale\',652,12141,5393,\'No\',0,0,\'2025-11-28\',\'New\');\nINSERT INTO "marketing" VALUES(100006,\'Male\',56,\'Hyderabad\',\'Mobile\',\'Google\',\'New Launch\',1308,18750,12018,\'No\',0,0,\'2025-01-29\',\'New\');\nINSERT INTO "marketing" VALUES(100007,\'Male\',20,\'Chennai\',\'Mobile\',\'Google\',\'Flash Sale\',1390,16858,25899,\'No\',0,0,\'2025-05-16\',\'New\');\nINSERT INTO "marketing" VALUES(100008,\'Male\',33,\'Hyderabad\',\'Mobile\',\'Facebook\',\'New Launch\',725,13587,14468,\'Yes\',5568,5568,\'2025-02-16\',\'Returning\');\nINSERT INTO "marketing" VALUES(100009,\'Male\',25,\'Delhi\',\'Mobile\',\'Facebook\',\'Summer Sale\',972,15837,18990,\'No\',0,0,\'2025-01-06\',\'New\');\nINSERT INTO "marketing" VALUES(100010,\'Male\',52,\'Chennai\',\'Desktop\',\'Instagram\',\'Flash Sale\',648,15367,10078,\'No\',0,0,\'2025-09-14\',\'New\');\nINSERT INTO "marketing" VALUES(100011,\'Male\',50,\'Pune\',\'Desktop\',\'Google\',\'Festive Offer\',537,5793,8837,\'No\',0,0,\'2025-01-01\',\'New\');\nINSERT INTO "marketing" VALUES(100012,\'Female\',49,\'Delhi\',\'Tablet\',\'Email\',\'Flash Sale\',1202,8392,23019,\'Yes\',4781,4781,\'2025-02-05\',\'New\');\nINSERT INTO "marketing" VALUES(100013,\'Male\',26,\'Hyderabad\',\'Tablet\',\'Google\',\'New Launch\',1969,18171,29609,\'No\',0,0,\'2025-07-24\',\'Returning\');\nINSERT INTO "marketing" VALUES(100014,\'Female\',46,\'Pune\',\'Mobile\',\'Google\',\'Summer Sale\',1856,19777,24898,\'Yes\',5969,5969,\'2025-01-31\',\'New\');\nINSERT INTO "marketing" VALUES(100015,\'Male\',22,\'Pune\',\'Desktop\',\'Google\',\'Festive Offer\',1138,16406,6961,\'No\',0,0,\'2025-10-20\',\'New\');\nINSERT INTO "marketing" VALUES(100016,\'Female\',33,\'Chennai\',\'Desktop\',\'Google\',\'Summer Sale\',1023,12109,11736,\'No\',0,0,\'2025-12-11\',\'Returning\');\nINSERT INTO "marketing" VALUES(100017,\'Male\',21,\'Bangalore\',\'Mobile\',\'Email\',\'Festive Offer\',1906,18073,20489,\'No\',0,0,\'2025-05-08\',\'New\');\nINSERT INTO "marketing" VALUES(100018,\'Male\',46,\'Chennai\',\'Desktop\',\'Google\',\'Summer Sale\',543,8245,6391,\'No\',0,0,\'2025-07-25\',\'Returning\');\nINSERT INTO "marketing" VALUES(100019,\'Male\',28,\'Mumbai\',\'Tablet\',\'Google\',\'New Launch\',1902,18711,22418,\'No\',0,0,\'2025-04-22\',\'New\');\nINSERT INTO "marketing" VALUES(100020,\'Male\',55,\'Hyderabad\',\'Mobile\',\'Instagram\',\'Summer Sale\',1587,16977,19834,\'Yes\',5704,5704,\'2025-02-11\',\'Returning\');\nINSERT INTO "marketing" VALUES(100021,\'Male\',22,\'Bangalore\',\'Mobile\',\'Google\',\'Summer Sale\',1374,19167,18565,\'No\',0,0,\'2025-08-03\',\'Returning\');\nINSERT INTO "marketing" VALUES(100022,\'Female\',34,\'Delhi\',\'Desktop\',\'Google\',\'New Launch\',897,10330,16921,\'No\',0,0,\'2025-01-05\',\'New\');\nINSERT INTO "marketing" VALUES(100023,\'Female\',57,\'Pune\',\'Tablet\',\'Google\',\'Festive Offer\',586,4840,10602,\'No\',0,0,\'2025-07-09\',\'New\');\nINSERT INTO "marketing" VALUES(100024,\'Female\',28,\'Bangalore\',\'Mobile\',\'Instagram\',\'Summer Sale\',1097,18673,16031,\'No\',0,0,\'2025-03-10\',\'Returning\');\nINSERT INTO "marketing" VALUES(100025,\'Female\',25,\'Pune\',\'Desktop\',\'Google\',\'Flash Sale\',805,11735,11388,\'No\',0,0,\'2025-09-08\',\'Returning\');\nINSERT INTO "marketing" VALUES(100026,\'Female\',21,\'Delhi\',\'Mobile\',\'Google\',\'Summer Sale\',477,4786,3907,\'No\',0,0,\'2025-10-10\',\'New\');\nINSERT INTO "marketing" VALUES(100027,\'Female\',53,\'Delhi\',\'Mobile\',\'Email\',\'Festive Offer\',1477,12598,9407,\'Yes\',3325,3325,\'2025-07-06\',\'New\');\nINSERT INTO "marketing" VALUES(100028,\'Male\',40,\'Delhi\',\'Mobile\',\'Google\',\'New Launch\',671,5564,5225,\'Yes\',2587,2587,\'2025-07-31\',\'Returning\');\nINSERT INTO "marketing" VALUES(100029,\'Male\',29,\'Hyderabad\',\'Mobile\',\'YouTube\',\'Festive Offer\',183,4042,845,\'No\',0,0,\'2025-04-13\',\'New\');\nINSERT INTO "marketing" VALUES(100030,\'Female\',40,\'Mumbai\',\'Desktop\',\'Google\',\'Summer Sale\',1052,13556,18756,\'No\',0,0,\'2025-05-23\',\'Returning\');\nINSERT INTO "marketing" VALUES(100031,\'Female\',59,\'Bangalore\',\'Mobile\',\'Email\',\'Flash Sale\',612,4279,5005,\'No\',0,0,\'2025-05-16\',\'Returning\');\nINSERT INTO "marketing" VALUES(100032,\'Male\',24,\'Bangalore\',\'Mobile\',\'Email\',\'New Launch\',1314,17258,24167,\'Yes\',1337,1337,\'2025-12-29\',\'Returning\');\nINSERT INTO "marketing" VALUES(100033,\'Female\',18,\'Bangalore\',\'Desktop\',\'Facebook\',\'Festive Offer\',227,2792,4252,\'No\',0,0,\'2025-12-06\',\'New\');\nINSERT INTO "marketing" VALUES(100034,\'Male\',37,\'Bangalore\',\'Mobile\',\'Instagram\',\'Flash Sale\',444,6786,8456,\'No\',0,0,\'2025-03-31\',\'Returning\');\nINSERT INTO "marketing" VALUES(100035,\'Female\',43,\'Bangalore\',\'Mobile\',\'Google\',\'New Launch\',967,11059,10709,\'Yes\',5377,5377,\'2025-03-28\',\'Returning\');\nINSERT INTO "marketing" VALUES(100036,\'Male\',36,\'Bangalore\',\'Mobile\',\'Instagram\',\'Festive Offer\',685,7861,4354,\'Yes\',5395,5395,\'2025-11-09\',\'Returning\');\nINSERT INTO "marketing" VALUES(100037,\'Male\',47,\'Bangalore\',\'Mobile\',\'Google\',\'New Launch\',548,8494,8221,\'No\',0,0,\'2025-02-24\',\'New\');\nINSERT INTO "marketing" VALUES(100038,\'Female\',32,\'Delhi\',\'Tablet\',\'Instagram\',\'Summer Sale\',302,4476,5080,\'No\',0,0,\'2025-10-14\',\'Returning\');\nINSERT INTO "marketing" VALUES(100039,\'Female\',46,\'Hyderabad\',\'Desktop\',\'Instagram\',\'New Launch\',1078,16054,17278,\'No\',0,0,\'2025-05-22\',\'Returning\');\nINSERT INTO "marketing" VALUES(100040,\'Female\',58,\'Mumbai\',\'Mobile\',\'Facebook\',\'Festive Offer\',865,10976,4575,\'Yes\',3937,3937,\'2025-12-22\',\'New\');\nINSERT INTO "marketing" VALUES(100041,\'Male\',31,\'Delhi\',\'Mobile\',\'Instagram\',\'New Launch\',910,14267,14848,\'No\',0,0,\'2025-01-11\',\'New\');\nINSERT INTO "marketing" VALUES(100042,\'Female\',48,\'Delhi\',\'Mobile\',\'Facebook\',\'New Launch\',1368,18395,25123,\'No\',0,0,\'2025-05-20\',\'New\');\nINSERT INTO "marketing" VALUES(100043,\'Female\',49,\'Delhi\',\'Mobile\',\'Facebook\',\'New Launch\',1267,15815,24949,\'No\',0,0,\'2025-07-21\',\'Returning\');\nINSERT INTO "marketing" VALUES(100044,\'Male\',23,\'Hyderabad\',\'Mobile\',\'Instagram\',\'Summer Sale\',604,11226,5574,\'No\',0,0,\'2025-07-14\',\'New\');\nINSERT INTO "marketing" VALUES(100045,\'Female\',44,\'Mumbai\',\'Mobile\',\'Google\',\'Summer Sale\',839,11967,4277,\'No\',0,0,\'2025-01-21\',\'Returning\');\nINSERT INTO "marketing" VALUES(100046,\'Male\',33,\'Delhi\',\'Mobile\',\'Google\',\'Festive Offer\',401,4248,3002,\'No\',0,0,\'2025-07-08\',\'New\');\nINSERT INTO "marketing" VALUES(100047,\'Male\',56,\'Hyderabad\',\'Desktop\',\'Google\',\'Festive Offer\',386,4042,7280,\'No\',0,0,\'2025-07-12\',\'Returning\');\nINSERT INTO "marketing" VALUES(100048,\'Female\',30,\'Delhi\',\'Desktop\',\'Facebook\',\'Summer Sale\',797,10382,10844,\'Yes\',6251,6251,\'2025-01-22\',\'Returning\');\nINSERT INTO "marketing" VALUES(100049,\'Female\',52,\'Bangalore\',\'Mobile\',\'Instagram\',\'Flash Sale\',1255,14264,7139,\'No\',0,0,\'2025-11-22\',\'New\');\nINSERT INTO "marketing" VALUES(100050,\'Female\',27,\'Bangalore\',\'Desktop\',\'YouTube\',\'Flash Sale\',1105,18134,12638,\'No\',0,0,\'2025-10-31\',\'Returning\');\nINSERT INTO "marketing" VALUES(100051,\'Female\',38,\'Chennai\',\'Desktop\',\'Google\',\'New Launch\',1494,15727,21948,\'No\',0,0,\'2025-09-11\',\'New\');\nINSERT INTO "marketing" VALUES(100052,\'Female\',29,\'Bangalore\',\'Mobile\',\'Google\',\'Flash Sale\',898,9552,11014,\'Yes\',3193,3193,\'2025-07-28\',\'Returning\');\nINSERT INTO "marketing" VALUES(100053,\'Female\',53,\'Chennai\',\'Desktop\',\'Facebook\',\'New Launch\',43,1065,324,\'No\',0,0,\'2025-06-06\',\'New\');\nINSERT INTO "marketing" VALUES(100054,\'Female\',48,\'Bangalore\',\'Mobile\',\'YouTube\',\'Flash Sale\',627,15368,5030,\'Yes\',2377,2377,\'2025-06-11\',\'New\');\nINSERT INTO "marketing" VALUES(100055,\'Male\',52,\'Pune\',\'Desktop\',\'Google\',\'New Launch\',2463,19819,30526,\'No\',0,0,\'2025-02-21\',\'New\');\nINSERT INTO "marketing" VALUES(100056,\'Male\',36,\'Mumbai\',\'Mobile\',\'Google\',\'Festive Offer\',214,2286,3243,\'Yes\',4821,4821,\'2025-02-22\',\'New\');\nINSERT INTO "marketing" VALUES(100057,\'Male\',54,\'Mumbai\',\'Mobile\',\'Instagram\',\'Summer Sale\',781,16154,3940,\'No\',0,0,\'2025-10-23\',\'New\');\nINSERT INTO "marketing" VALUES(100058,\'Male\',27,\'Delhi\',\'Mobile\',\'Instagram\',\'Festive Offer\',1073,14137,17867,\'No\',0,0,\'2025-09-25\',\'New\');\nINSERT INTO "marketing" VALUES(100059,\'Female\',46,\'Pune\',\'Mobile\',\'Facebook\',\'New Launch\',161,2473,2550,\'No\',0,0,\'2025-04-17\',\'New\');\nINSERT INTO "marketing" VALUES(100060,\'Male\',34,\'Hyderabad\',\'Mobile\',\'Google\',\'Summer Sale\',1200,13886,16201,\'No\',0,0,\'2025-04-29\',\'New\');\nINSERT INTO "marketing" VALUES(100061,\'Female\',36,\'Hyderabad\',\'Mobile\',\'Facebook\',\'Flash Sale\',1342,19826,25415,\'No\',0,0,\'2025-10-06\',\'Returning\');\nINSERT INTO "marketing" VALUES(100062,\'Male\',59,\'Delhi\',\'Mobile\',\'Google\',\'Summer Sale\',1024,10579,17600,\'No\',0,0,\'2025-08-13\',\'New\');\nINSERT INTO "marketing" VALUES(100063,\'Male\',47,\'Hyderabad\',\'Desktop\',\'YouTube\',\'New Launch\',118,1806,1858,\'No\',0,0,\'2025-01-14\',\'New\');\nINSERT INTO "marketing" VALUES(100064,\'Male\',32,\'Pune\',\'Desktop\',\'Instagram\',\'Summer Sale\',693,9331,11233,\'Yes\',5808,5808,\'2025-11-30\',\'Returning\');\nINSERT INTO "marketing" VALUES(100065,\'Female\',35,\'Delhi\',\'Mobile\',\'Facebook\',\'New Launch\',838,15901,7820,\'No\',0,0,\'2025-03-24\',\'Returning\');\nINSERT INTO "marketing" VALUES(100066,\'Female\',44,\'Hyderabad\',\'Mobile\',\'YouTube\',\'Summer Sale\',433,10806,2535,\'No\',0,0,\'2025-09-21\',\'New\');\nINSERT INTO "marketing" VALUES(100067,\'Male\',60,\'Chennai\',\'Mobile\',\'Google\',\'Flash Sale\',1667,16834,26938,\'Yes\',6093,6093,\'2025-03-09\',\'Returning\');\nINSERT INTO "marketing" VALUES(100068,\'Female\',46,\'Pune\',\'Mobile\',\'Google\',\'Festive Offer\',1000,10682,12836,\'Yes\',1988,1988,\'2025-08-25\',\'Returning\');\nINSERT INTO "marketing" VALUES(100069,\'Male\',59,\'Chennai\',\'Mobile\',\'Facebook\',\'Flash Sale\',1354,16310,10696,\'No\',0,0,\'2025-07-16\',\'New\');\nINSERT INTO "marketing" VALUES(100070,\'Male\',56,\'Bangalore\',\'Desktop\',\'Email\',\'Flash Sale\',1351,14096,22431,\'No\',0,0,\'2025-01-02\',\'Returning\');\nINSERT INTO "marketing" VALUES(100071,\'Female\',37,\'Chennai\',\'Mobile\',\'Facebook\',\'Festive Offer\',860,16370,11034,\'No\',0,0,\'2025-08-22\',\'New\');\nINSERT INTO "marketing" VALUES(100072,\'Female\',30,\'Pune\',\'Mobile\',\'Instagram\',\'New Launch\',1303,15998,22128,\'No\',0,0,\'2025-12-06\',\'New\');\nINSERT INTO "marketing" VALUES(100073,\'Male\',49,\'Pune\',\'Mobile\',\'YouTube\',\'Flash Sale\',507,14927,9413,\'Yes\',2277,2277,\'2025-07-29\',\'Returning\');\nINSERT INTO "marketing" VALUES(100074,\'Male\',22,\'Bangalore\',\'Tablet\',\'Instagram\',\'New Launch\',1010,11266,17926,\'No\',0,0,\'2025-06-12\',\'Returning\');\nINSERT INTO "marketing" VALUES(100075,\'Female\',52,\'Delhi\',\'Mobile\',\'Facebook\',\'Flash Sale\',196,3461,1092,\'No\',0,0,\'2025-02-21\',\'Returning\');\nINSERT INTO "marketing" VALUES(100076,\'Female\',28,\'Hyderabad\',\'Tablet\',\'Google\',\'Summer Sale\',1086,12782,8587,\'No\',0,0,\'2025-12-16\',\'New\');\nINSERT INTO "marketing" VALUES(100077,\'Male\',28,\'Delhi\',\'Mobile\',\'Instagram\',\'Festive Offer\',980,19608,11150,\'No\',0,0,\'2025-05-11\',\'New\');\nINSERT INTO "marketing" VALUES(100078,\'Male\',47,\'Pune\',\'Mobile\',\'Google\',\'New Launch\',1492,19753,28933,\'No\',0,0,\'2025-08-22\',\'Returning\');\nINSERT INTO "marketing" VALUES(100079,\'Female\',30,\'Pune\',\'Desktop\',\'Google\',\'New Launch\',1455,19335,22099,\'Yes\',4648,4648,\'2025-05-21\',\'Returning\');\nINSERT INTO "marketing" VALUES(100080,\'Male\',54,\'Chennai\',\'Desktop\',\'YouTube\',\'New Launch\',602,9878,4624,\'No\',0,0,\'2025-04-23\',\'Returning\');\nINSERT INTO "marketing" VALUES(100081,\'Male\',57,\'Mumbai\',\'Desktop\',\'Facebook\',\'Festive Offer\',91,1791,1005,\'No\',0,0,\'2025-03-09\',\'Returning\');\nINSERT INTO "marketing" VALUES(100082,\'Male\',36,\'Mumbai\',\'Mobile\',\'Google\',\'Flash Sale\',1073,9430,8703,\'No\',0,0,\'2025-09-04\',\'New\');\nINSERT INTO "marketing" VALUES(100083,\'Female\',39,\'Chennai\',\'Mobile\',\'Google\',\'Festive Offer\',1671,13522,28195,\'No\',0,0,\'2025-07-22\',\'Returning\');\nINSERT INTO "marketing" VALUES(100084,\'Male\',34,\'Bangalore\',\'Mobile\',\'Facebook\',\'Flash Sale\',522,12672,4040,\'Yes\',6208,6208,\'2025-06-17\',\'Returning\');\nINSERT INTO "marketing" VALUES(100085,\'Male\',59,\'Delhi\',\'Desktop\',\'YouTube\',\'Flash Sale\',153,4323,2928,\'No\',0,0,\'2025-09-10\',\'Returning\');\nINSERT INTO "marketing" VALUES(100086,\'Male\',24,\'Mumbai\',\'Mobile\',\'Instagram\',\'Flash Sale\',1191,18201,18908,\'Yes\',4827,4827,\'2025-12-02\',\'Returning\');\nINSERT INTO "marketing" VALUES(100087,\'Male\',49,\'Hyderabad\',\'Tablet\',\'Google\',\'Flash Sale\',1845,15071,32632,\'Yes\',3809,3809,\'2025-10-06\',\'New\');\nINSERT INTO "marketing" VALUES(100088,\'Female\',21,\'Mumbai\',\'Mobile\',\'Google\',\'New Launch\',746,7450,10111,\'Yes\',3532,3532,\'2025-05-05\',\'New\');\nINSERT INTO "marketing" VALUES(100089,\'Male\',54,\'Delhi\',\'Desktop\',\'Instagram\',\'Festive Offer\',491,8134,3123,\'No\',0,0,\'2025-01-02\',\'Returning\');\nINSERT INTO "marketing" VALUES(100090,\'Female\',27,\'Pune\',\'Mobile\',\'Email\',\'Summer Sale\',104,1344,1012,\'No\',0,0,\'2025-10-29\',\'Returning\');\nINSERT INTO "marketing" VALUES(100091,\'Female\',19,\'Delhi\',\'Mobile\',\'Facebook\',\'Summer Sale\',926,16105,9067,\'No\',0,0,\'2025-08-20\',\'Returning\');\nINSERT INTO "marketing" VALUES(100092,\'Male\',57,\'Delhi\',\'Desktop\',\'Email\',\'Flash Sale\',108,1520,1259,\'No\',0,0,\'2025-12-18\',\'New\');\nINSERT INTO "marketing" VALUES(100093,\'Male\',49,\'Hyderabad\',\'Mobile\',\'Email\',\'Flash Sale\',204,2652,2853,\'No\',0,0,\'2025-12-31\',\'Returning\');\nINSERT INTO "marketing" VALUES(100094,\'Female\',42,\'Pune\',\'Mobile\',\'Instagram\',\'New Launch\',381,4249,5491,\'No\',0,0,\'2025-04-21\',\'New\');\nINSERT INTO "marketing" VALUES(100095,\'Female\',46,\'Pune\',\'Mobile\',\'Email\',\'New Launch\',338,3615,3042,\'No\',0,0,\'2025-03-20\',\'New\');\nINSERT INTO "marketing" VALUES(100096,\'Female\',22,\'Delhi\',\'Mobile\',\'Instagram\',\'Flash Sale\',849,18731,16390,\'No\',0,0,\'2025-12-10\',\'Returning\');\nINSERT INTO "marketing" VALUES(100097,\'Male\',44,\'Mumbai\',\'Mobile\',\'Facebook\',\'Summer Sale\',567,10738,7510,\'Yes\',5462,5462,\'2025-04-25\',\'Returning\');\nINSERT INTO "marketing" VALUES(100098,\'Male\',40,\'Chennai\',\'Mobile\',\'Facebook\',\'Festive Offer\',1562,18881,26702,\'No\',0,0,\'2025-11-26\',\'Returning\');\nINSERT INTO "marketing" VALUES(100099,\'Male\',56,\'Pune\',\'Desktop\',\'Google\',\'Festive Offer\',1278,10624,12289,\'No\',0,0,\'2025-03-15\',\'New\');\nINSERT INTO "marketing" VALUES(100100,\'Female\',22,\'Delhi\',\'Mobile\',\'Google\',\'Festive Offer\',1206,15365,11964,\'No\',0,0,\'2025-10-18\',\'New\');\nINSERT INTO "marketing" VALUES(100101,\'Male\',21,\'Delhi\',\'Desktop\',\'Google\',\'Summer Sale\',1280,14394,14173,\'No\',0,0,\'2025-09-20\',\'New\');\nINSERT INTO "marketing" VALUES(100102,\'Male\',40,\'Bangalore\',\'Mobile\',\'Facebook\',\'New Launch\',404,10606,4170,\'No\',0,0,\'2025-01-04\',\'New\');\nINSERT INTO "marketing" VALUES(100103,\'Male\',37,\'Pune\',\'Desktop\',\'Facebook\',\'Flash Sale\',45,753,490,\'No\',0,0,\'2025-09-30\',\'New\');\nINSERT INTO "marketing" VALUES(100104,\'Male\',50,\'Bangalore\',\'Mobile\',\'Instagram\',\'New Launch\',125,1886,1419,\'Yes\',3868,3868,\'2025-10-22\',\'Returning\');\nINSERT INTO "marketing" VALUES(100105,\'Female\',54,\'Bangalore\',\'Mobile\',\'Google\',\'New Launch\',739,11142,14160,\'No\',0,0,\'2025-12-20\',\'New\');\nINSERT INTO "marketing" VALUES(100106,\'Female\',23,\'Bangalore\',\'Mobile\',\'Instagram\',\'New Launch\',1222,13468,19469,\'No\',0,0,\'2025-03-28\',\'New\');\nINSERT INTO "marketing" VALUES(100107,\'Male\',50,\'Hyderabad\',\'Mobile\',\'Google\',\'Flash Sale\',379,5339,2404,\'No\',0,0,\'2025-11-05\',\'New\');\nINSERT INTO "marketing" VALUES(100108,\'Male\',59,\'Delhi\',\'Tablet\',\'Facebook\',\'New Launch\',1121,19488,21059,\'No\',0,0,\'2025-11-22\',\'Returning\');\nINSERT INTO "marketing" VALUES(100109,\'Female\',58,\'Mumbai\',\'Mobile\',\'Instagram\',\'Flash Sale\',897,19879,10869,\'No\',0,0,\'2025-08-20\',\'Returning\');\nINSERT INTO "marketing" VALUES(100110,\'Male\',21,\'Mumbai\',\'Mobile\',\'Facebook\',\'Summer Sale\',932,17115,12381,\'No\',0,0,\'2025-01-22\',\'Returning\');\nINSERT INTO "marketing" VALUES(100111,\'Female\',54,\'Hyderabad\',\'Mobile\',\'Instagram\',\'Festive Offer\',729,15262,13403,\'No\',0,0,\'2025-02-13\',\'Returning\');\nINSERT INTO "marketing" VALUES(100112,\'Male\',20,\'Mumbai\',\'Mobile\',\'Instagram\',\'Festive Offer\',622,9769,10195,\'No\',0,0,\'2025-01-27\',\'New\');\nINSERT INTO "marketing" VALUES(100113,\'Female\',22,\'Mumbai\',\'Mobile\',\'Instagram\',\'Flash Sale\',329,5427,4383,\'Yes\',4214,4214,\'2025-06-08\',\'Returning\');\nINSERT INTO "marketing" VALUES(100114,\'Female\',26,\'Bangalore\',\'Tablet\',\'Instagram\',\'New Launch\',985,11263,14501,\'No\',0,0,\'2025-12-17\',\'Returning\');\nINSERT INTO "marketing" VALUES(100115,\'Male\',59,\'Hyderabad\',\'Mobile\',\'Google\',\'Flash Sale\',590,7518,9592,\'No\',0,0,\'2025-03-12\',\'New\');\nINSERT INTO "marketing" VALUES(100116,\'Male\',22,\'Mumbai\',\'Desktop\',\'Instagram\',\'Summer Sale\',361,4794,2334,\'Yes\',6804,6804,\'2025-03-26\',\'Returning\');\nINSERT INTO "marketing" VALUES(100117,\'Female\',20,\'Bangalore\',\'Mobile\',\'Google\',\'New Launch\',1077,15210,8429,\'No\',0,0,\'2025-08-29\',\'Returning\');\nINSERT INTO "marketing" VALUES(100118,\'Male\',41,\'Hyderabad\',\'Mobile\',\'Instagram\',\'Flash Sale\',1214,16979,23624,\'No\',0,0,\'2025-11-06\',\'Returning\');\nINSERT INTO "marketing" VALUES(100119,\'Male\',34,\'Delhi\',\'Mobile\',\'Instagram\',\'Summer Sale\',1560,17405,13355,\'No\',0,0,\'2025-05-20\',\'Returning\');\nINSERT INTO "marketing" VALUES(100120,\'Female\',50,\'Delhi\',\'Mobile\',\'YouTube\',\'Festive Offer\',803,11955,8542,\'No\',0,0,\'2025-07-11\',\'Returning\');\nINSERT INTO "marketing" VALUES(100121,\'Male\',42,\'Pune\',\'Mobile\',\'Google\',\'Summer Sale\',1274,11486,7900,\'No\',0,0,\'2025-08-30\',\'Returning\');\nINSERT INTO "marketing" VALUES(100122,\'Male\',48,\'Bangalore\',\'Mobile\',\'Google\',\'Flash Sale\',504,5399,7880,\'No\',0,0,\'2025-02-26\',\'New\');\nINSERT INTO "marketing" VALUES(100123,\'Female\',33,\'Mumbai\',\'Mobile\',\'Instagram\',\'New Launch\',1272,16878,5422,\'No\',0,0,\'2025-05-04\',\'New\');\nINSERT INTO "marketing" VALUES(100124,\'Male\',36,\'Bangalore\',\'Mobile\',\'Google\',\'New Launch\',3

In [ ]:
# Create Db
conn = sqlite3.connect(":memory:")
conn.executescript(sql_script)

In [ ]:
# Helper function
def sql(query):
  return pd.read_sql(query, conn)

In [ ]:
# Check for db table
sql("SELECT name FROM sqlite_master Where type = 'table' ;")

        name
0  marketing

In [ ]:
# Total records
sql("SELECT COUNT(*) FROM marketing;")

   COUNT(*)
0      5000

## **Where**

In [ ]:
sql("SELECT * FROM marketing WHERE city = 'Delhi' ;")

,Customer_ID,Gender,Age,City,Device,Marketing_Channel,Campaign,Ad_Clicks,Impressions,Spend,Purchased,Sales,Order_Value,Purchase_Date,Customer_Segment
0,100002,Male,53,Delhi,Mobile,Instagram,Festive Offer,839,9615,3443,No,0,0,2025-12-24,New
1,100004,Female,52,Delhi,Tablet,Google,Flash Sale,1180,12350,18022,Yes,3065,3065,2025-05-29,Returning
2,100009,Male,25,Delhi,Mobile,Facebook,Summer Sale,972,15837,18990,No,0,0,2025-01-06,New
3,100012,Female,49,Delhi,Tablet,Email,Flash Sale,1202,8392,23019,Yes,4781,4781,2025-02-05,New
4,100022,Female,34,Delhi,Desktop,Google,New Launch,897,10330,16921,No,0,0,2025-01-05,New
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1113,104977,Female,60,Delhi,Mobile,Google,Festive Offer,772,8874,12239,No,0,0,2025-08-19,New
1114,104979,Male,48,Delhi,Mobile,Google,Festive Offer,818,9426,8260,No,0,0,2025-03-19,Returning
1115,104988,Male,36,Delhi,Tablet,Facebook,Flash Sale,106,1361,467,Yes,1009,1009,2025-09-05,New
1116,104990,Female,29,Delhi,Mobile,Google,Summer Sale,1864,18442,21271,No,0,0,2025-09-01,Returning
1117,104991,Male,36,Delhi,Desktop,YouTube,Festive Offer,604,15473,7180,No,0,0,2025-07-19,New

### **Comparison Operators**

| Operator     | Meaning                  |
| ------------ | ------------------------ |
| `=`          | Equal to                 |
| `>`          | Greater than             |
| `<`          | Less than                |
| `>=`         | Greater than or equal to |
| `<=`         | Less than or equal to    |
| `!=` or `<>` | Not equal to             |

In [ ]:
sql("SELECT * from Marketing WHERE Spend >5000 ;")

,Customer_ID,Gender,Age,City,Device,Marketing_Channel,Campaign,Ad_Clicks,Impressions,Spend,Purchased,Sales,Order_Value,Purchase_Date,Customer_Segment
0,100001,Male,19,Hyderabad,Mobile,Google,Summer Sale,1106,18370,11890,Yes,2979,2979,2025-04-30,Returning
1,100004,Female,52,Delhi,Tablet,Google,Flash Sale,1180,12350,18022,Yes,3065,3065,2025-05-29,Returning
2,100005,Male,32,Chennai,Mobile,Instagram,Flash Sale,652,12141,5393,No,0,0,2025-11-28,New
3,100006,Male,56,Hyderabad,Mobile,Google,New Launch,1308,18750,12018,No,0,0,2025-01-29,New
4,100007,Male,20,Chennai,Mobile,Google,Flash Sale,1390,16858,25899,No,0,0,2025-05-16,New
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3248,104995,Female,37,Hyderabad,Mobile,Email,Summer Sale,1521,13007,12124,No,0,0,2025-12-25,Returning
3249,104997,Female,35,Mumbai,Mobile,Email,Festive Offer,1275,13245,14945,No,0,0,2025-05-11,Returning
3250,104998,Female,44,Hyderabad,Desktop,Facebook,Flash Sale,840,13488,15588,Yes,1839,1839,2025-09-27,Returning
3251,104999,Male,35,Mumbai,Mobile,Instagram,Flash Sale,1323,16568,7926,No,0,0,2025-10-29,New
3252,105000,Female,19,Mumbai,Mobile,Instagram,New Launch,453,10302,8163,Yes,3002,3002,2025-06-27,New

### **AND, OR, NOT**

- AND

Both conditions must be true.

- OR

At least one condition must be true.

- OR

At least one condition must be true.

In [ ]:
# And
sql("SELECT * from marketing WHERE city = 'Delhi' AND Purchased = 'Yes' ;")

,Customer_ID,Gender,Age,City,Device,Marketing_Channel,Campaign,Ad_Clicks,Impressions,Spend,Purchased,Sales,Order_Value,Purchase_Date,Customer_Segment
0,100004,Female,52,Delhi,Tablet,Google,Flash Sale,1180,12350,18022,Yes,3065,3065,2025-05-29,Returning
1,100012,Female,49,Delhi,Tablet,Email,Flash Sale,1202,8392,23019,Yes,4781,4781,2025-02-05,New
2,100027,Female,53,Delhi,Mobile,Email,Festive Offer,1477,12598,9407,Yes,3325,3325,2025-07-06,New
3,100028,Male,40,Delhi,Mobile,Google,New Launch,671,5564,5225,Yes,2587,2587,2025-07-31,Returning
4,100048,Female,30,Delhi,Desktop,Facebook,Summer Sale,797,10382,10844,Yes,6251,6251,2025-01-22,Returning
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,104945,Male,56,Delhi,Mobile,Instagram,Summer Sale,229,2777,1441,Yes,3067,3067,2025-09-03,Returning
183,104954,Female,34,Delhi,Mobile,Instagram,Flash Sale,109,2582,1351,Yes,1894,1894,2025-08-16,Returning
184,104962,Male,56,Delhi,Mobile,YouTube,Flash Sale,1095,16477,16425,Yes,5902,5902,2025-09-03,Returning
185,104976,Male,33,Delhi,Desktop,Google,Festive Offer,85,1078,1211,Yes,4566,4566,2025-11-17,New
186,104988,Male,36,Delhi,Tablet,Facebook,Flash Sale,106,1361,467,Yes,1009,1009,2025-09-05,New

In [ ]:
# Or
sql("SELECT * from marketing WHERE Marketing_Channel = 'Google' OR Marketing_Channel = 'Instagram';")

,Customer_ID,Gender,Age,City,Device,Marketing_Channel,Campaign,Ad_Clicks,Impressions,Spend,Purchased,Sales,Order_Value,Purchase_Date,Customer_Segment
0,100001,Male,19,Hyderabad,Mobile,Google,Summer Sale,1106,18370,11890,Yes,2979,2979,2025-04-30,Returning
1,100002,Male,53,Delhi,Mobile,Instagram,Festive Offer,839,9615,3443,No,0,0,2025-12-24,New
2,100004,Female,52,Delhi,Tablet,Google,Flash Sale,1180,12350,18022,Yes,3065,3065,2025-05-29,Returning
3,100005,Male,32,Chennai,Mobile,Instagram,Flash Sale,652,12141,5393,No,0,0,2025-11-28,New
4,100006,Male,56,Hyderabad,Mobile,Google,New Launch,1308,18750,12018,No,0,0,2025-01-29,New
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2924,104990,Female,29,Delhi,Mobile,Google,Summer Sale,1864,18442,21271,No,0,0,2025-09-01,Returning
2925,104992,Male,50,Bangalore,Mobile,Instagram,Flash Sale,1152,12411,7613,No,0,0,2025-05-07,New
2926,104993,Female,38,Hyderabad,Mobile,Instagram,Flash Sale,561,10052,10587,No,0,0,2025-10-08,New
2927,104999,Male,35,Mumbai,Mobile,Instagram,Flash Sale,1323,16568,7926,No,0,0,2025-10-29,New
2928,105000,Female,19,Mumbai,Mobile,Instagram,New Launch,453,10302,8163,Yes,3002,3002,2025-06-27,New

In [ ]:
# Not
sql("SELECT * from marketing WHERE Not City = 'Delhi' ;")

,Customer_ID,Gender,Age,City,Device,Marketing_Channel,Campaign,Ad_Clicks,Impressions,Spend,Purchased,Sales,Order_Value,Purchase_Date,Customer_Segment
0,100001,Male,19,Hyderabad,Mobile,Google,Summer Sale,1106,18370,11890,Yes,2979,2979,2025-04-30,Returning
1,100003,Female,39,Mumbai,Mobile,Facebook,Summer Sale,195,3669,1853,No,0,0,2025-01-23,New
2,100005,Male,32,Chennai,Mobile,Instagram,Flash Sale,652,12141,5393,No,0,0,2025-11-28,New
3,100006,Male,56,Hyderabad,Mobile,Google,New Launch,1308,18750,12018,No,0,0,2025-01-29,New
4,100007,Male,20,Chennai,Mobile,Google,Flash Sale,1390,16858,25899,No,0,0,2025-05-16,New
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3877,104996,Female,54,Hyderabad,Mobile,YouTube,Summer Sale,34,532,245,No,0,0,2025-05-28,New
3878,104997,Female,35,Mumbai,Mobile,Email,Festive Offer,1275,13245,14945,No,0,0,2025-05-11,Returning
3879,104998,Female,44,Hyderabad,Desktop,Facebook,Flash Sale,840,13488,15588,Yes,1839,1839,2025-09-27,Returning
3880,104999,Male,35,Mumbai,Mobile,Instagram,Flash Sale,1323,16568,7926,No,0,0,2025-10-29,New
3881,105000,Female,19,Mumbai,Mobile,Instagram,New Launch,453,10302,8163,Yes,3002,3002,2025-06-27,New

In [ ]:
# Between
sql("SELECT * from marketing WHERE Spend BETWEEN 5000 AND 10000 ;")

,Customer_ID,Gender,Age,City,Device,Marketing_Channel,Campaign,Ad_Clicks,Impressions,Spend,Purchased,Sales,Order_Value,Purchase_Date,Customer_Segment
0,100005,Male,32,Chennai,Mobile,Instagram,Flash Sale,652,12141,5393,No,0,0,2025-11-28,New
1,100011,Male,50,Pune,Desktop,Google,Festive Offer,537,5793,8837,No,0,0,2025-01-01,New
2,100015,Male,22,Pune,Desktop,Google,Festive Offer,1138,16406,6961,No,0,0,2025-10-20,New
3,100018,Male,46,Chennai,Desktop,Google,Summer Sale,543,8245,6391,No,0,0,2025-07-25,Returning
4,100027,Female,53,Delhi,Mobile,Email,Festive Offer,1477,12598,9407,Yes,3325,3325,2025-07-06,New
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1405,104991,Male,36,Delhi,Desktop,YouTube,Festive Offer,604,15473,7180,No,0,0,2025-07-19,New
1406,104992,Male,50,Bangalore,Mobile,Instagram,Flash Sale,1152,12411,7613,No,0,0,2025-05-07,New
1407,104994,Female,26,Pune,Mobile,YouTube,Flash Sale,814,13750,8806,No,0,0,2025-03-02,Returning
1408,104999,Male,35,Mumbai,Mobile,Instagram,Flash Sale,1323,16568,7926,No,0,0,2025-10-29,New
1409,105000,Female,19,Mumbai,Mobile,Instagram,New Launch,453,10302,8163,Yes,3002,3002,2025-06-27,New

In [ ]:
# In
sql("SELECT * from marketing WHERE Marketing_Channel = 'Google' OR Marketing_Channel = 'Instagram';")

,Customer_ID,Gender,Age,City,Device,Marketing_Channel,Campaign,Ad_Clicks,Impressions,Spend,Purchased,Sales,Order_Value,Purchase_Date,Customer_Segment
0,100001,Male,19,Hyderabad,Mobile,Google,Summer Sale,1106,18370,11890,Yes,2979,2979,2025-04-30,Returning
1,100002,Male,53,Delhi,Mobile,Instagram,Festive Offer,839,9615,3443,No,0,0,2025-12-24,New
2,100004,Female,52,Delhi,Tablet,Google,Flash Sale,1180,12350,18022,Yes,3065,3065,2025-05-29,Returning
3,100005,Male,32,Chennai,Mobile,Instagram,Flash Sale,652,12141,5393,No,0,0,2025-11-28,New
4,100006,Male,56,Hyderabad,Mobile,Google,New Launch,1308,18750,12018,No,0,0,2025-01-29,New
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2924,104990,Female,29,Delhi,Mobile,Google,Summer Sale,1864,18442,21271,No,0,0,2025-09-01,Returning
2925,104992,Male,50,Bangalore,Mobile,Instagram,Flash Sale,1152,12411,7613,No,0,0,2025-05-07,New
2926,104993,Female,38,Hyderabad,Mobile,Instagram,Flash Sale,561,10052,10587,No,0,0,2025-10-08,New
2927,104999,Male,35,Mumbai,Mobile,Instagram,Flash Sale,1323,16568,7926,No,0,0,2025-10-29,New
2928,105000,Female,19,Mumbai,Mobile,Instagram,New Launch,453,10302,8163,Yes,3002,3002,2025-06-27,New

In [ ]:
sql("SELECT * from marketing WHERE Marketing_Channel IN ('Google','Instagram');")

,Customer_ID,Gender,Age,City,Device,Marketing_Channel,Campaign,Ad_Clicks,Impressions,Spend,Purchased,Sales,Order_Value,Purchase_Date,Customer_Segment
0,100001,Male,19,Hyderabad,Mobile,Google,Summer Sale,1106,18370,11890,Yes,2979,2979,2025-04-30,Returning
1,100002,Male,53,Delhi,Mobile,Instagram,Festive Offer,839,9615,3443,No,0,0,2025-12-24,New
2,100004,Female,52,Delhi,Tablet,Google,Flash Sale,1180,12350,18022,Yes,3065,3065,2025-05-29,Returning
3,100005,Male,32,Chennai,Mobile,Instagram,Flash Sale,652,12141,5393,No,0,0,2025-11-28,New
4,100006,Male,56,Hyderabad,Mobile,Google,New Launch,1308,18750,12018,No,0,0,2025-01-29,New
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2924,104990,Female,29,Delhi,Mobile,Google,Summer Sale,1864,18442,21271,No,0,0,2025-09-01,Returning
2925,104992,Male,50,Bangalore,Mobile,Instagram,Flash Sale,1152,12411,7613,No,0,0,2025-05-07,New
2926,104993,Female,38,Hyderabad,Mobile,Instagram,Flash Sale,561,10052,10587,No,0,0,2025-10-08,New
2927,104999,Male,35,Mumbai,Mobile,Instagram,Flash Sale,1323,16568,7926,No,0,0,2025-10-29,New
2928,105000,Female,19,Mumbai,Mobile,Instagram,New Launch,453,10302,8163,Yes,3002,3002,2025-06-27,New

### **LIKE**

Used for pattern matching.

| Pattern | Meaning       |
| ------- | ------------- |
| `A%`    | Starts with A |
| `%A`    | Ends with A   |
| `%A%`   | Contains A    |

In [ ]:
sql("SELECT * from marketing WHERE Campaign LIKE '%Sale%' ;")

,Customer_ID,Gender,Age,City,Device,Marketing_Channel,Campaign,Ad_Clicks,Impressions,Spend,Purchased,Sales,Order_Value,Purchase_Date,Customer_Segment
0,100001,Male,19,Hyderabad,Mobile,Google,Summer Sale,1106,18370,11890,Yes,2979,2979,2025-04-30,Returning
1,100003,Female,39,Mumbai,Mobile,Facebook,Summer Sale,195,3669,1853,No,0,0,2025-01-23,New
2,100004,Female,52,Delhi,Tablet,Google,Flash Sale,1180,12350,18022,Yes,3065,3065,2025-05-29,Returning
3,100005,Male,32,Chennai,Mobile,Instagram,Flash Sale,652,12141,5393,No,0,0,2025-11-28,New
4,100007,Male,20,Chennai,Mobile,Google,Flash Sale,1390,16858,25899,No,0,0,2025-05-16,New
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2537,104994,Female,26,Pune,Mobile,YouTube,Flash Sale,814,13750,8806,No,0,0,2025-03-02,Returning
2538,104995,Female,37,Hyderabad,Mobile,Email,Summer Sale,1521,13007,12124,No,0,0,2025-12-25,Returning
2539,104996,Female,54,Hyderabad,Mobile,YouTube,Summer Sale,34,532,245,No,0,0,2025-05-28,New
2540,104998,Female,44,Hyderabad,Desktop,Facebook,Flash Sale,840,13488,15588,Yes,1839,1839,2025-09-27,Returning
2541,104999,Male,35,Mumbai,Mobile,Instagram,Flash Sale,1323,16568,7926,No,0,0,2025-10-29,New

### **ORDER BY**

Used to sort records.
- ASC = ascending
- DESC = descending

In [ ]:
sql("SELECT * from marketing ORDER BY Spend DESC ;")

,Customer_ID,Gender,Age,City,Device,Marketing_Channel,Campaign,Ad_Clicks,Impressions,Spend,Purchased,Sales,Order_Value,Purchase_Date,Customer_Segment
0,100253,Male,19,Pune,Desktop,Google,New Launch,2473,19636,48430,Yes,2775,2775,2025-05-17,New
1,104975,Male,29,Mumbai,Mobile,Email,Summer Sale,2390,19300,47789,Yes,5372,5372,2025-03-31,New
2,104414,Male,26,Mumbai,Mobile,Google,New Launch,2348,19239,45697,No,0,0,2025-07-10,Returning
3,102567,Female,37,Delhi,Desktop,Email,New Launch,2554,17414,45276,No,0,0,2025-12-30,New
4,104623,Female,26,Mumbai,Mobile,Email,Summer Sale,2373,16077,44596,No,0,0,2025-12-20,New
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,100726,Female,20,Delhi,Mobile,Google,Festive Offer,36,502,170,No,0,0,2025-05-31,New
4996,104196,Male,35,Mumbai,Mobile,Instagram,Flash Sale,40,502,166,No,0,0,2025-09-12,Returning
4997,102762,Male,25,Delhi,Mobile,YouTube,Festive Offer,32,605,162,No,0,0,2025-10-20,New
4998,102955,Male,24,Hyderabad,Mobile,Facebook,New Launch,34,950,139,Yes,6400,6400,2025-11-24,Returning
4999,102022,Male,31,Mumbai,Mobile,Facebook,Summer Sale,21,567,91,No,0,0,2025-11-28,Returning

In [ ]:
# Purchased = Yes
sql("SELECT * FROM marketing WHERE Purchased = 'Yes';")

,Customer_ID,Gender,Age,City,Device,Marketing_Channel,Campaign,Ad_Clicks,Impressions,Spend,Purchased,Sales,Order_Value,Purchase_Date,Customer_Segment
0,100001,Male,19,Hyderabad,Mobile,Google,Summer Sale,1106,18370,11890,Yes,2979,2979,2025-04-30,Returning
1,100004,Female,52,Delhi,Tablet,Google,Flash Sale,1180,12350,18022,Yes,3065,3065,2025-05-29,Returning
2,100008,Male,33,Hyderabad,Mobile,Facebook,New Launch,725,13587,14468,Yes,5568,5568,2025-02-16,Returning
3,100012,Female,49,Delhi,Tablet,Email,Flash Sale,1202,8392,23019,Yes,4781,4781,2025-02-05,New
4,100014,Female,46,Pune,Mobile,Google,Summer Sale,1856,19777,24898,Yes,5969,5969,2025-01-31,New
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
907,104985,Male,54,Pune,Tablet,Facebook,New Launch,427,7919,2378,Yes,1591,1591,2025-10-06,New
908,104988,Male,36,Delhi,Tablet,Facebook,Flash Sale,106,1361,467,Yes,1009,1009,2025-09-05,New
909,104989,Female,28,Bangalore,Desktop,Google,Summer Sale,355,4079,5833,Yes,3262,3262,2025-04-24,New
910,104998,Female,44,Hyderabad,Desktop,Facebook,Flash Sale,840,13488,15588,Yes,1839,1839,2025-09-27,Returning
911,105000,Female,19,Mumbai,Mobile,Instagram,New Launch,453,10302,8163,Yes,3002,3002,2025-06-27,New