<a href="https://colab.research.google.com/github/prasadnikhil125-CHAUDHARY/business-data-analysis-ai-ml/blob/main/machine_learning_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Machine Learning**

In [1]:
# Step 1: Import library
import pandas as pd

https://github.com/YBIFoundation/Dataset/blob/main/Salary%20Data.csv

https://github.com/YBIFoundation/Dataset/raw/main/Salary%20Data.csv

In [2]:
# Step 2: Read dataset
df = pd.read_csv('https://raw.githubusercontent.com/YBIFoundation/Dataset/main/Ice%20Cream.csv')

In [3]:
df.head()

   Temperature  Revenue
0         24.6      535
1         26.1      626
2         27.8      661
3         20.6      488
4         11.6      317

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Temperature  500 non-null    float64
 1   Revenue      500 non-null    int64
dtypes: float64(1), int64(1)
memory usage: 7.9 KB

In [5]:
df.describe()

       Temperature      Revenue
count   500.000000   500.000000
mean     22.281600   522.058000
std       8.097597   175.410399
min       0.000000    10.000000
25%      17.175000   406.000000
50%      22.400000   530.000000
75%      27.800000   643.000000
max      45.000000  1000.000000

In [6]:
# Step 3: Define y (output) and X (input)
df.columns

Index(['Temperature', 'Revenue'], dtype='object')

In [7]:
y = df['Revenue']
X = df[['Temperature']]

In [8]:
# Step 4: Train test split
from sklearn.model_selection import train_test_split

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=2529)

In [10]:
df.shape, X.shape, X_train.shape, X_test.shape

((500, 2), (500, 1), (375, 1), (125, 1))

In [11]:
# Step 5: Select model
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [12]:
# Step 6: Train model
model.fit(X_train,y_train)

LinearRegression()

In [13]:
model.intercept_

np.float64(44.018097590245816)

In [14]:
model.coef_

array([21.4695184])

In [15]:
# Step 7: Prediction
y_pred = model.predict(X_test)

In [16]:
# Step 8: Evaluation
from sklearn.metrics import mean_absolute_percentage_error

In [17]:
mean_absolute_percentage_error(y_test,y_pred)

0.04155209268159155